#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const serverDir = resolve(here, "..");
const rootDir = resolve(serverDir, "..");
const devVarsPath = resolve(serverDir, ".dev.vars");
const firmwarePath = resolve(rootDir, "main", "firmware_private.h");
const defaultApiBase = "https://eva-todo-api.example.workers.dev/api/v1";
const args = parseArgs(process.argv.slice(2));

function makeToken() {
  return "eva_" + randomBytes(24).toString("base64url");
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) continue;
    const key = a.slice(2);
    out[key] = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "1";
  }
  return out;
}

function decodeMaybe(name) {
  const envName = name.replaceAll("-", "_").toUpperCase();
  const b64 = args[name + "-b64"];
  if (b64) return Buffer.from(b64, "base64").toString("utf8");
  return args[name] || process.env[envName] || "";
}

function parseDevVars(text) {
  const vars = {};
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) vars[m[1]] = m[2];
  }
  return vars;
}

let vars = {};
if (existsSync(devVarsPath)) {
  vars = parseDevVars(readFileSync(devVarsPath, "utf8"));
}
vars.ADMIN_TOKEN ||= makeToken();
vars.DEVICE_TOKEN ||= makeToken();

writeFileSync(devVarsPath, "ADMIN_TOKEN=" + vars.ADMIN_TOKEN + "\nDEVICE_TOKEN=" + vars.DEVICE_TOKEN + "\n");

const wifiSsid = decodeMaybe("wifi-ssid") || "CHANGE_ME";
const wifiPassword = decodeMaybe("wifi-password") || "CHANGE_ME";
const apiBase = decodeMaybe("api-base-url") || defaultApiBase;
const deviceId = decodeMaybe("device-id") || "ai-passport-001";

mkdirSync(dirname(firmwarePath), { recursive: true });
writeFileSync(
  firmwarePath,
  [
    "// Generated by server/scripts/init-secrets.mjs. Ignored by Git.",
    "#pragma once",
    "",
    "#define TODO_WIFI_SSID " + JSON.stringify(wifiSsid),
    "#define TODO_WIFI_PASSWORD " + JSON.stringify(wifiPassword),
    "#define TODO_API_BASE_URL " + JSON.stringify(apiBase),
    "#define TODO_API_TOKEN " + JSON.stringify(vars.DEVICE_TOKEN),
    "#define TODO_DEVICE_ID " + JSON.stringify(deviceId),
    ""
  ].join("\n")
);

console.log("Created/updated server/.dev.vars and main/firmware_private.h");
console.log("Secret values were written only to ignored local files.");
